Atualiza HU 004 e 005.
gilmarioArantes/cs-2022-1_g4 pull request #9
Opened 2022-07-04 03:45 UTC by FA101

2022-07-04 12:27 UTC, JoaoMario17 requested changes

2022-07-04 12:27 UTC, JoaoMario17 commented on HU/HU04.md
> +#HISTÓRIAS DE USUÁRIOS
Acho interessante corrigir a sintaxe utilizada nos arquivos .md, acrescentando um espaço aṕos o caractere "#" :

# H1
## H2
### H3

2022-07-05 10:12 UTC, ghfmartins approved these changes

2022-07-05 23:19 UTC, tmarcorf approved these changes
Ok.

2022-07-06 00:17 UTC, jefferson-pereira approved these changes

2022-07-06 00:19 UTC, merged